package net.liplum.blocks.tmtrainer;

import arc.math.Mathf;

public class RandomName {
    /*
        Generated by tools/src/RandomName.py
     */
    public static char[] AllChars = {
            'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L',
            'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
            'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
            'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
            'w', 'x', 'y',
            '%', '&', '$', '@', '#', '~', '*', '§', '|', '?', '!'
    };

    public static String one(int length) {
        StringBuilder b = new StringBuilder();
        for (int i = 0; i < length; i++) {
            int index = Mathf.random(0, AllChars.length - 1);
            b.append(AllChars[index]);
        }
        return b.toString();
    }
}
